// site/src/components/livekit/SettingsMenu.vue
<template>
  <div class="settings-menu lk-settings-menu">
    <div class="lk-settings-tabs">
      <button
        v-for="tab in tabs"
        :key="tab"
        type="button"
        class="lk-button lk-tab"
        :aria-pressed="activeTab === tab"
        @click="activeTab = tab">
        {{ settings[tab].label }}
      </button>
    </div>
    <div class="tab-content">
      <template v-if="activeTab === 'media'">
        <template v-if="settings.media?.camera">
          <h3>Камера</h3>
          <section>
            <CameraSettings />
          </section>
        </template>
        <template v-if="settings.media?.microphone">
          <h3>Мікрофон</h3>
          <section>
            <MicrophoneSettings />
          </section>
        </template>
        <template v-if="settings.media?.speaker">
          <h3>Динаміки</h3>
          <section class="lk-button-group">
            <span class="lk-button">Аудіо вихід</span>
            <MediaDeviceMenu kind="audiooutput" />
          </section>
        </template>
      </template>
      <template v-if="activeTab === 'recording'">
        <h3>Запис зустрічі</h3>
        <section>
          <p>
            {{ isRecording ? 'Зустріч зараз записується' : 'Немає активного запису' }}
          </p>
          <button type="button" class="lk-button" :disabled="processingRecRequest" @click="toggleRoomRecording">
            {{ isRecording ? 'Зупинити' : 'Почати' }} запис
          </button>
        </section>
      </template>
    </div>
    <div class="lk-settings-footer">
      <button type="button" class="lk-button" @click="$emit('close')">Закрити</button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { useRoom } from '@/composables/useRoom'
import { useIsRecording } from '@/composables/useIsRecording'
import MediaDeviceMenu from './MediaDeviceMenu.vue'
import CameraSettings from './CameraSettings.vue'
import MicrophoneSettings from './MicrophoneSettings.vue'

defineEmits(['close'])

const room = useRoom()
const recordingEndpoint = import.meta.env.VITE_LK_RECORD_ENDPOINT

const settings = computed(() => ({
  media: { camera: true, microphone: true, label: 'Медіа', speaker: true },
  recording: recordingEndpoint ? { label: 'Запис' } : undefined
}))

const tabs = computed(() =>
  Object.keys(settings.value).filter(t => settings.value[t] !== undefined && settings.value[t] !== null)
)

const activeTab = ref(tabs.value[0] ?? 'media')
const isRecording = useIsRecording()
const initialRecStatus = ref(isRecording.value)
const processingRecRequest = ref(false)

watch(
  () => isRecording.value,
  v => {
    if (initialRecStatus.value !== v) processingRecRequest.value = false
  }
)

async function toggleRoomRecording() {
  if (!recordingEndpoint) {
    throw new TypeError('No recording endpoint specified')
  }
  processingRecRequest.value = true
  initialRecStatus.value = isRecording.value
  const url = isRecording.value
    ? `${recordingEndpoint}/stop?roomName=${room.name}`
    : `${recordingEndpoint}/start?roomName=${room.name}`
  const response = await fetch(url)
  if (!response.ok) {
    console.error('Error handling recording request', response.status, response.statusText)
    processingRecRequest.value = false
  }
}
</script>

<style scoped>
.lk-settings-menu {
  width: 100%;
  max-width: 480px;
  max-height: 90vh;
  overflow-y: auto;
  background: var(--lk-bg2, #1a1a1a);
  padding: 1rem;
  border-radius: 8px;
}
.lk-settings-tabs {
  display: flex;
  gap: 0.25rem;
  margin-bottom: 1rem;
}
.lk-tab {
  padding: 0.5rem;
  border-radius: 0;
  border-bottom: 3px solid var(--bg5, #333);
}
.lk-tab[aria-pressed='true'] {
  border-color: var(--lk-accent-bg);
}
.tab-content h3 {
  margin: 0.5rem 0 0.25rem;
  font-size: 1rem;
}
.tab-content section {
  margin-bottom: 1rem;
}
.lk-settings-footer {
  display: flex;
  justify-content: flex-end;
  width: 100%;
  margin-top: 1rem;
}
</style>

// site/src/lib/SettingsMenu.jsx
import * as React from 'react'
import { useMaybeLayoutContext, MediaDeviceMenu, useRoomContext, useIsRecording } from '@livekit/components-react'
import styles from '@/styles/SettingsMenu.module.css'
import { CameraSettings } from '@/lib/CameraSettings'
import { MicrophoneSettings } from '@/lib/MicrophoneSettings'

export function SettingsMenu(props) {
  const layoutContext = useMaybeLayoutContext()
  const room = useRoomContext()
  const recordingEndpoint = import.meta.env.VITE_LK_RECORD_ENDPOINT

  const settings = React.useMemo(() => {
    return {
      media: { camera: true, microphone: true, label: 'Media Devices', speaker: true },
      recording: recordingEndpoint ? { label: 'Recording' } : undefined
    }
  }, [recordingEndpoint])

  const tabs = React.useMemo(() => Object.keys(settings).filter(t => settings[t] !== undefined), [settings])
  const [activeTab, setActiveTab] = React.useState(tabs[0])

  const isRecording = useIsRecording()
  const [initialRecStatus, setInitialRecStatus] = React.useState(isRecording)
  const [processingRecRequest, setProcessingRecRequest] = React.useState(false)

  React.useEffect(() => {
    if (initialRecStatus !== isRecording) {
      setProcessingRecRequest(false)
    }
  }, [isRecording, initialRecStatus])

  const toggleRoomRecording = async () => {
    if (!recordingEndpoint) {
      throw TypeError('No recording endpoint specified')
    }
    setProcessingRecRequest(true)
    setInitialRecStatus(isRecording)
    let response
    if (isRecording) {
      response = await fetch(recordingEndpoint + `/stop?roomName=${room.name}`)
    } else {
      response = await fetch(recordingEndpoint + `/start?roomName=${room.name}`)
    }
    if (!response.ok) {
      console.error('Error handling recording request, check server logs:', response.status, response.statusText)
      setProcessingRecRequest(false)
    }
  }

  return (
    <div className='settings-menu' style={{ width: '100%', position: 'relative' }} {...props}>
      <div className={styles.tabs}>
        {tabs.map(
          tab =>
            settings[tab] && (
              <button
                className={`${styles.tab} lk-button`}
                key={tab}
                onClick={() => setActiveTab(tab)}
                aria-pressed={tab === activeTab}>
                {settings[tab].label}
              </button>
            )
        )}
      </div>
      <div className='tab-content'>
        {activeTab === 'media' && (
          <>
            {settings.media?.camera && (
              <>
                <h3>Camera</h3>
                <section>
                  <CameraSettings />
                </section>
              </>
            )}
            {settings.media?.microphone && (
              <>
                <h3>Microphone</h3>
                <section>
                  <MicrophoneSettings />
                </section>
              </>
            )}
            {settings.media?.speaker && (
              <>
                <h3>Speaker & Headphones</h3>
                <section className='lk-button-group'>
                  <span className='lk-button'>Audio Output</span>
                  <div className='lk-button-group-menu'>
                    <MediaDeviceMenu kind='audiooutput'></MediaDeviceMenu>
                  </div>
                </section>
              </>
            )}
          </>
        )}
        {activeTab === 'recording' && (
          <>
            <h3>Record Meeting</h3>
            <section>
              <p>{isRecording ? 'Meeting is currently being recorded' : 'No active recordings for this meeting'}</p>
              <button disabled={processingRecRequest} onClick={() => toggleRoomRecording()}>
                {isRecording ? 'Stop' : 'Start'} Recording
              </button>
            </section>
          </>
        )}
      </div>
      <div style={{ display: 'flex', justifyContent: 'flex-end', width: '100%' }}>
        <button className='lk-button' onClick={() => layoutContext?.widget.dispatch?.({ msg: 'toggle_settings' })}>
          Close
        </button>
      </div>
    </div>
  )
}
