// site/src/components/livekit/MicrophoneSettings.vue
<template>
  <div class="lk-microphone-settings">
    <section class="lk-button-group">
      <TrackToggle source="microphone" label="Мікрофон" />
      <MediaDeviceMenu kind="audioinput" />
    </section>
    <button
      type="button"
      class="lk-button"
      :disabled="isNoiseFilterPending"
      :aria-pressed="isNoiseFilterEnabled"
      @click="setNoiseFilterEnabled(!isNoiseFilterEnabled)">
      {{ isNoiseFilterEnabled ? 'Вимкнути' : 'Увімкнути' }} шумозаглушення
    </button>
  </div>
</template>

<script setup>
import { onMounted } from 'vue'
import { useKrispNoiseFilter } from '@/composables/useKrispNoiseFilter'
import { isLowPowerDevice } from '@/lib/client-utils'
import TrackToggle from './TrackToggle.vue'
import MediaDeviceMenu from './MediaDeviceMenu.vue'

const { isNoiseFilterEnabled, setNoiseFilterEnabled, isNoiseFilterPending } = useKrispNoiseFilter({
  filterOptions: {
    bufferOverflowMs: 100,
    bufferDropMs: 200,
    quality: isLowPowerDevice() ? 'low' : 'medium',
    onBufferDrop: () => {
      console.warn('krisp buffer dropped')
    }
  }
})

onMounted(() => {
  setNoiseFilterEnabled(!isLowPowerDevice())
})
</script>

<style scoped>
.lk-microphone-settings {
  display: flex;
  flex-direction: row;
  gap: 10px;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
}
</style>

// site/lib/MicrophoneSettings.tsx
import React from 'react'
import { useKrispNoiseFilter } from '@livekit/components-react/krisp'
import { TrackToggle, MediaDeviceMenu } from '@livekit/components-react'
import { Track } from 'livekit-client'
import { isLowPowerDevice } from './client-utils'

export function MicrophoneSettings() {
  const { isNoiseFilterEnabled, setNoiseFilterEnabled, isNoiseFilterPending } = useKrispNoiseFilter({
    filterOptions: {
      bufferOverflowMs: 100,
      bufferDropMs: 200,
      quality: isLowPowerDevice() ? 'low' : 'medium',
      onBufferDrop: () => {
        console.warn('krisp buffer dropped, noise filter versions >= 0.3.2 will automatically disable the filter')
      }
    }
  })

  React.useEffect(() => {
    // enable Krisp by default on non-low power devices
    setNoiseFilterEnabled(!isLowPowerDevice())
  }, [])
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'row',
        gap: '10px',
        alignItems: 'center',
        justifyContent: 'space-between'
      }}>
      <section className='lk-button-group'>
        <TrackToggle source={Track.Source.Microphone}>Microphone</TrackToggle>
        <div className='lk-button-group-menu'>
          <MediaDeviceMenu kind='audioinput' />
        </div>
      </section>

      <button
        type='button'
        className='lk-button'
        onClick={() => setNoiseFilterEnabled(!isNoiseFilterEnabled)}
        disabled={isNoiseFilterPending}
        aria-pressed={isNoiseFilterEnabled}>
        {isNoiseFilterEnabled ? 'Disable' : 'Enable'} Enhanced Noise Cancellation
      </button>
    </div>
  )
}
