// site/src/lib/CameraSettings.jsx
import React from 'react'
import { MediaDeviceMenu, TrackToggle, useLocalParticipant, VideoTrack } from '@livekit/components-react'
import { BackgroundBlur, VirtualBackground } from '@livekit/track-processors'
import { isLocalTrack, Track } from 'livekit-client'

const BACKGROUND_IMAGES = [
  { name: 'Desk', path: '/background-images/samantha-gades-BlIhVfXbi9s-unsplash.jpg' },
  { name: 'Nature', path: '/background-images/ali-kazal-tbw_KQE3Cbg-unsplash.jpg' }
]

export function CameraSettings() {
  const { cameraTrack, localParticipant } = useLocalParticipant()
  const [backgroundType, setBackgroundType] = React.useState(
    cameraTrack?.track?.getProcessor()?.name === 'background-blur'
      ? 'blur'
      : cameraTrack?.track?.getProcessor()?.name === 'virtual-background'
        ? 'image'
        : 'none'
  )

  const [virtualBackgroundImagePath, setVirtualBackgroundImagePath] = React.useState(null)

  const camTrackRef = React.useMemo(() => {
    return cameraTrack
      ? { participant: localParticipant, publication: cameraTrack, source: Track.Source.Camera }
      : undefined
  }, [localParticipant, cameraTrack])

  const selectBackground = (type, imagePath) => {
    setBackgroundType(type)
    if (type === 'image' && imagePath) {
      setVirtualBackgroundImagePath(imagePath)
    } else if (type !== 'image') {
      setVirtualBackgroundImagePath(null)
    }
  }

  React.useEffect(() => {
    if (isLocalTrack(cameraTrack?.track)) {
      if (backgroundType === 'blur') {
        cameraTrack.track?.setProcessor(BackgroundBlur())
      } else if (backgroundType === 'image' && virtualBackgroundImagePath) {
        cameraTrack.track?.setProcessor(VirtualBackground(virtualBackgroundImagePath))
      } else {
        cameraTrack.track?.stopProcessor()
      }
    }
  }, [cameraTrack, backgroundType, virtualBackgroundImagePath])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      {camTrackRef && (
        <VideoTrack
          style={{
            maxHeight: '280px',
            objectFit: 'contain',
            objectPosition: 'right',
            transform: 'scaleX(-1)'
          }}
          trackRef={camTrackRef}
        />
      )}

      <section className='lk-button-group'>
        <TrackToggle source={Track.Source.Camera}>Camera</TrackToggle>
        <div className='lk-button-group-menu'>
          <MediaDeviceMenu kind='videoinput' />
        </div>
      </section>

      <div style={{ marginTop: '10px' }}>
        <div style={{ marginBottom: '8px' }}>Background Effects</div>
        <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
          <button
            onClick={() => selectBackground('none')}
            className='lk-button'
            aria-pressed={backgroundType === 'none'}
            style={{
              border: backgroundType === 'none' ? '2px solid #0090ff' : '1px solid #d1d1d1',
              minWidth: '80px'
            }}>
            None
          </button>

          <button
            onClick={() => selectBackground('blur')}
            className='lk-button'
            aria-pressed={backgroundType === 'blur'}
            style={{
              border: backgroundType === 'blur' ? '2px solid #0090ff' : '1px solid #d1d1d1',
              minWidth: '80px',
              backgroundColor: '#f0f0f0',
              position: 'relative',
              overflow: 'hidden',
              height: '60px'
            }}>
            <div
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                backgroundColor: '#e0e0e0',
                filter: 'blur(8px)',
                zIndex: 0
              }}
            />
            <span
              style={{
                position: 'relative',
                zIndex: 1,
                backgroundColor: 'rgba(0,0,0,0.6)',
                padding: '2px 5px',
                borderRadius: '4px',
                fontSize: '12px'
              }}>
              Blur
            </span>
          </button>

          {BACKGROUND_IMAGES.map(image => (
            <button
              key={image.path}
              onClick={() => selectBackground('image', image.path)}
              className='lk-button'
              aria-pressed={backgroundType === 'image' && virtualBackgroundImagePath === image.path}
              style={{
                backgroundImage: `url(${image.path})`,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                width: '80px',
                height: '60px',
                border:
                  backgroundType === 'image' && virtualBackgroundImagePath === image.path
                    ? '2px solid #0090ff'
                    : '1px solid #d1d1d1'
              }}>
              <span
                style={{
                  backgroundColor: 'rgba(0,0,0,0.6)',
                  padding: '2px 5px',
                  borderRadius: '4px',
                  fontSize: '12px'
                }}>
                {image.name}
              </span>
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

// site/src/components/livekit/CameraSettings.vue
<template>
  <div class="lk-camera-settings">
    <VideoTrack v-if="camTrackRef" :track-ref="camTrackRef" :style="previewStyle" />
    <section class="lk-button-group">
      <TrackToggle source="camera" label="Камера" />
      <MediaDeviceMenu kind="videoinput" />
    </section>
    <div class="lk-background-effects">
      <div class="lk-background-label">Фон</div>
      <div class="lk-background-buttons">
        <button
          type="button"
          class="lk-button lk-bg-btn"
          :aria-pressed="backgroundType === 'none'"
          :class="{ active: backgroundType === 'none' }"
          @click="selectBackground('none')">
          Немає
        </button>
        <button
          type="button"
          class="lk-button lk-bg-btn lk-bg-blur"
          :aria-pressed="backgroundType === 'blur'"
          :class="{ active: backgroundType === 'blur' }"
          @click="selectBackground('blur')">
          <span class="lk-bg-blur-preview" />
          <span class="lk-bg-label">Размиття</span>
        </button>
        <button
          v-for="img in backgroundImages"
          :key="img.path"
          type="button"
          class="lk-button lk-bg-btn lk-bg-img"
          :aria-pressed="backgroundType === 'image' && virtualBackgroundImagePath === img.path"
          :class="{ active: backgroundType === 'image' && virtualBackgroundImagePath === img.path }"
          :style="{ backgroundImage: `url(${img.path})` }"
          @click="selectBackground('image', img.path)">
          <span class="lk-bg-label">{{ img.name }}</span>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { useLocalParticipant } from '@/composables/useLocalParticipant'
import { BackgroundBlur, VirtualBackground } from '@livekit/track-processors'
import { isLocalTrack, Track } from 'livekit-client'
import VideoTrack from './VideoTrack.vue'
import TrackToggle from './TrackToggle.vue'
import MediaDeviceMenu from './MediaDeviceMenu.vue'

const BACKGROUND_IMAGES = [
  { name: 'Desk', path: '/background-images/samantha-gades-BlIhVfXbi9s-unsplash.jpg' },
  { name: 'Nature', path: '/background-images/ali-kazal-tbw_KQE3Cbg-unsplash.jpg' }
]

const { cameraTrack, localParticipant } = useLocalParticipant()

const backgroundType = ref('none')
const virtualBackgroundImagePath = ref(null)

const camTrackRef = computed(() => {
  if (!cameraTrack.value) return null
  return {
    participant: localParticipant,
    publication: cameraTrack.value,
    source: Track.Source.Camera
  }
})

const previewStyle = {
  maxHeight: '280px',
  objectFit: 'contain',
  objectPosition: 'right',
  transform: 'scaleX(-1)'
}

function selectBackground(type, imagePath) {
  backgroundType.value = type
  if (type === 'image' && imagePath) {
    virtualBackgroundImagePath.value = imagePath
  } else if (type !== 'image') {
    virtualBackgroundImagePath.value = null
  }
}

watch(
  [cameraTrack, backgroundType, virtualBackgroundImagePath],
  ([cam, type, path]) => {
    const track = cam?.track
    if (track && isLocalTrack(track)) {
      if (type === 'blur') {
        track.setProcessor?.(BackgroundBlur())
      } else if (type === 'image' && path) {
        track.setProcessor?.(VirtualBackground(path))
      } else {
        track.stopProcessor?.()
      }
    }
  },
  { immediate: true }
)
</script>

<style scoped>
.lk-camera-settings {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
.lk-background-effects {
  margin-top: 10px;
}
.lk-background-label {
  margin-bottom: 8px;
}
.lk-background-buttons {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}
.lk-bg-btn {
  min-width: 80px;
  height: 60px;
  border: 1px solid #d1d1d1;
  position: relative;
  overflow: hidden;
}
.lk-bg-btn.active {
  border: 2px solid #0090ff;
}
.lk-bg-blur {
  background-color: #f0f0f0;
}
.lk-bg-blur-preview {
  position: absolute;
  inset: 0;
  background: #e0e0e0;
  filter: blur(8px);
  z-index: 0;
}
.lk-bg-img {
  background-size: cover;
  background-position: center;
  width: 80px;
}
.lk-bg-label {
  position: relative;
  z-index: 1;
  background: rgba(0, 0, 0, 0.6);
  padding: 2px 5px;
  border-radius: 4px;
  font-size: 12px;
}
</style>
