// site/src/lib/KeyboardShortcuts.jsx
import React from 'react'
import { Track } from 'livekit-client'
import { useTrackToggle } from '@livekit/components-react'

export function KeyboardShortcuts() {
  const { toggle: toggleMic } = useTrackToggle({ source: Track.Source.Microphone })
  const { toggle: toggleCamera } = useTrackToggle({ source: Track.Source.Camera })

  React.useEffect(() => {
    function handleShortcut(event) {
      if (toggleMic && event.key === 'A' && (event.ctrlKey || event.metaKey)) {
        event.preventDefault()
        toggleMic()
      }
      if (event.key === 'V' && (event.ctrlKey || event.metaKey)) {
        event.preventDefault()
        toggleCamera()
      }
    }

    window.addEventListener('keydown', handleShortcut)
    return () => window.removeEventListener('keydown', handleShortcut)
  }, [toggleMic, toggleCamera])

  return null
}

// site/src/components/livekit/KeyboardShortcuts.vue
<template><!-- без UI --></template>

<script setup>
import { onMounted, onUnmounted } from 'vue'
import { useTrackToggle } from '@/composables/useTrackToggle'
import { Track } from 'livekit-client'

const { toggle: toggleMic } = useTrackToggle({ source: Track.Source.Microphone })
const { toggle: toggleCamera } = useTrackToggle({ source: Track.Source.Camera })

function handleShortcut(event) {
  if (toggleMic && event.key === 'a' && (event.ctrlKey || event.metaKey)) {
    event.preventDefault()
    toggleMic()
  }
  if (event.key === 'v' && (event.ctrlKey || event.metaKey)) {
    event.preventDefault()
    toggleCamera()
  }
}

onMounted(() => {
  window.addEventListener('keydown', handleShortcut)
})
onUnmounted(() => {
  window.removeEventListener('keydown', handleShortcut)
})
</script>
